import { mkdirSync, createWriteStream, writeFileSync } from "node:fs";
import { createServiceClient } from "../src/lib/supabase/public";

/**
 * An off-platform copy of the data that cannot be regenerated.
 *
 * WHY THIS EXISTS. The production project is on a plan with NO automatic
 * database backups: `supabase backups list` returns an empty list and
 * `pitr_enabled: false`. The worst case today is not "lose an hour" — it is
 * total, unrecoverable loss of every project, conversation and publication.
 * Until the plan changes, this script IS the backup.
 *
 * WHAT IT COPIES, and what it deliberately does not:
 *
 *   projects                  the generated application source lives here; this
 *                             is the irreplaceable one
 *   project_publications      what is live, and under which slug
 *   project_ai_conversations  the conversation a project was built through
 *   project_ai_messages       and its turns
 *   project_ai_memory         what Ventrio remembers about each project
 *   profiles                  names, preferences, plan and locale
 *   project_responses         what real visitors sent through a published form
 *   project_feedback_analyses derived, but expensive to recreate
 *
 * NOT copied, on purpose:
 *   auth.users        Supabase owns it; the service role cannot dump it through
 *                     PostgREST, and restoring users is a Supabase-side action.
 *                     Recorded in the runbook as the gap it is.
 *   generation_jobs   operational state. A restored queue would re-run finished
 *                     work and re-spend quota.
 *   storage objects   `project-thumbnails` is regenerated by the worker from
 *                     the projects rows this file already contains, and
 *                     `project-proofs` is empty. Nothing to preserve.
 *
 * Output is NDJSON, one row per line, so a partial file is still a usable file
 * and a large table never has to be held in memory at once.
 *
 *   npx tsx --env-file=.env.local --conditions=react-server scripts/backup.mts
 *
 * Writes to `backups/<timestamp>/`, which is gitignored. Credentials come from
 * the environment and are never written to the output.
 */

const TABLES = [
  "projects",
  "project_publications",
  "project_ai_conversations",
  "project_ai_messages",
  "project_ai_memory",
  "profiles",
  "project_responses",
  "project_feedback_analyses",
] as const;

/** Rows per request. Large enough to be quick, small enough to stay bounded. */
const PAGE = 500;

if (!process.env.SUPABASE_SERVICE_ROLE_KEY || !process.env.NEXT_PUBLIC_SUPABASE_URL) {
  console.error("backup: needs NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const supabase = createServiceClient();
const stamp = new Date().toISOString().replace(/[:.]/g, "-");
const dir = new URL(`../backups/${stamp}/`, import.meta.url);
mkdirSync(dir, { recursive: true });

const manifest: Record<string, { rows: number; bytes: number; complete: boolean }> = {};
let failed = false;

for (const table of TABLES) {
  const file = new URL(`${table}.ndjson`, dir);
  const out = createWriteStream(file);
  let from = 0;
  let rows = 0;
  let bytes = 0;
  let complete = true;

  /**
   * Paging needs a stable order, and not every table is keyed the same way —
   * `project_feedback_analyses` has no `id` column at all, which silently
   * failed the whole table on the first run. The first column that exists wins;
   * unordered paging is the last resort and is still correct for a full dump,
   * just not guaranteed stable if rows are written mid-run.
   */
  const orderCandidates: (string | null)[] = ["id", "created_at", null];
  let orderIndex = 0;
  let order: string | null = orderCandidates[0];

  for (;;) {
    let query = supabase.from(table).select("*").range(from, from + PAGE - 1);
    if (order) query = query.order(order, { ascending: true });
    const { data, error } = await query;

    if (error) {
      /* An unknown ordering column is a schema fact, not a failure: try the
         next one before giving up on the table. */
      if (/column .* does not exist/i.test(error.message) && orderIndex < orderCandidates.length - 1) {
        orderIndex += 1;
        order = orderCandidates[orderIndex];
        continue;
      }
      console.error(`  ${table}: FAILED at offset ${from} — ${error.message}`);
      complete = false;
      failed = true;
      break;
    }
    if (!data || data.length === 0) break;

    for (const row of data) {
      const line = `${JSON.stringify(row)}\n`;
      out.write(line);
      bytes += Buffer.byteLength(line);
      rows += 1;
    }
    if (data.length < PAGE) break;
    from += PAGE;
  }

  await new Promise<void>((resolve) => out.end(resolve));
  manifest[table] = { rows, bytes, complete };
  console.log(`  ${table.padEnd(28)} ${String(rows).padStart(6)} rows  ${String(Math.round(bytes / 1024)).padStart(6)} kB${complete ? "" : "  INCOMPLETE"}`);
}

/**
 * The manifest is what makes a restore verifiable: a dump nobody can check is
 * a dump nobody should trust.
 */
writeFileSync(
  new URL("manifest.json", dir),
  `${JSON.stringify({
    takenAt: new Date().toISOString(),
    project: process.env.NEXT_PUBLIC_SUPABASE_URL,
    tables: manifest,
    notCovered: ["auth.users", "generation_jobs", "storage objects"],
    complete: !failed,
  }, null, 2)}\n`,
);

console.log(`\n${failed ? "COMPLETED WITH ERRORS" : "OK"} — backups/${stamp}/`);
process.exit(failed ? 1 : 0);
