import { headers } from "next/headers";
import { getPublicProject } from "@/lib/publishing/queries";
import { isPublicSlug } from "@/lib/publishing/slug";
import { buildGeneratedApp } from "@/lib/v2/app/pipeline";

/**
 * The sandbox document for a published application, as its own response.
 *
 * WHY THIS EXISTS AT ALL, because it reverses a decision recorded in
 * `sandbox.ts` and that reversal should be legible.
 *
 * The document used to be embedded in `/p/[slug]`. React Server Components
 * serialise the whole server tree as flight data alongside the HTML, so a 2.4 MB
 * document became 5.6 MB of markup — the same bytes twice — parsed in one go on
 * a route that is dynamic and therefore pays it on every single visit. Desktop
 * absorbed that. A real iPhone did not: the published app showed "Starting the
 * app…" indefinitely and then WebKit's "This page couldn't load", which is an
 * out-of-memory kill. The same app rendered fine in the workspace on the same
 * phone, where the preview is behind a toggle and the frame is never
 * server-rendered.
 *
 * Fetching it separately makes the page ~60 kB and the document one streamed
 * response, parsed once.
 *
 * WHAT THE ORIGINAL DECISION WAS PROTECTING, and why this does not break it.
 * `sandbox.ts` argues that `srcdoc` is stronger than a preview origin because
 * the generated bytes never get "a fetchable, linkable, indexable address".
 * The property that actually matters is that model-written code must never be
 * loadable as a *document* on Ventrio's origin, because then it would run
 * unsandboxed with Ventrio's cookies. Three things keep that true here:
 *
 *   1. `Content-Type: text/plain`. Opening this URL shows inert text; a browser
 *      will not execute it as a page.
 *   2. `X-Content-Type-Options: nosniff`, so no browser may decide otherwise.
 *      Without this, (1) is a suggestion.
 *   3. `X-Robots-Tag: noindex, nofollow`, so it is not indexable.
 *
 * The frame itself is unchanged: still `srcdoc`, still `allow-scripts
 * allow-forms` with no `allow-same-origin`, still an opaque origin with no route
 * back to Ventrio. And the bytes were already public — this is the document of
 * an application its owner chose to publish.
 *
 * THE NONCE. A `srcdoc` frame inherits the *embedding page's* CSP, and Ventrio
 * allows scripts only by nonce. This response is a different request from the
 * page, so the nonce baked in here is not the one the page runs under. The
 * client re-stamps it with `withLiveNonce` before setting `srcdoc` — the same
 * mechanism the workspace has used since `router.refresh()` first broke the
 * preview. A nonce is written here anyway, so there is something to re-stamp
 * and so the document is coherent if read directly.
 */

/** Never prerendered: the publication and the nonce are both per-request. */
export const dynamic = "force-dynamic";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ slug: string }> },
): Promise<Response> {
  const { slug } = await params;

  // The same gate `/p/[slug]` applies. A document is only ever served for a
  // publication that is actually live.
  if (!isPublicSlug(slug)) return notFound();
  const publication = await getPublicProject(slug);
  if (!publication?.app) return notFound();

  const nonce = (await headers()).get("x-nonce") ?? undefined;
  const built = await buildGeneratedApp(publication.app, { nonce });
  // A publication that no longer compiles is absent rather than a page of build
  // errors — the same choice `/p/[slug]` makes.
  if (!built.ok) return notFound();

  return new Response(built.document, {
    status: 200,
    headers: {
      // Inert by declaration, and nosniff so that is not merely advisory.
      "Content-Type": "text/plain; charset=utf-8",
      "X-Content-Type-Options": "nosniff",
      "X-Robots-Tag": "noindex, nofollow",
      // Rebuilt per request like the page it belongs to; the nonce it carries
      // is this request's and is replaced on the client regardless.
      "Cache-Control": "no-store",
      // It is only ever read by Ventrio's own page, from the same origin.
      "Cross-Origin-Resource-Policy": "same-origin",
    },
  });
}

function notFound(): Response {
  return new Response("Not found", {
    status: 404,
    headers: { "Content-Type": "text/plain; charset=utf-8", "X-Content-Type-Options": "nosniff" },
  });
}
