/**
 * What the model is told, generated from the gate's own constants.
 *
 * Every list here is derived rather than hand-written. A prompt that advertises
 * a library the allowlist refuses, or omits one it permits, costs a paid
 * request to discover — the codegen canary lost three generations to exactly
 * this class of drift between what was asked for and what was accepted.
 *
 * The prompt describes a contract and a set of capabilities. It does not
 * describe a product, a page, a set of sections or a layout, because the entire
 * point of replacing the page schema was to stop doing that. What to build is
 * the brief's business; how to structure it is the model's.
 */

import { ALLOWED_EXTENSIONS, ALLOWED_PATH_ROOTS, APP_BUDGETS, APP_SCHEMA_VERSION, RESERVED_PATHS } from "./contract";
import { PATCH_SCHEMA_VERSION } from "./edit";
import { describeRuntime, RUNTIME_TEMPLATES, type RuntimeTemplateId } from "./runtime";

export function appSystemPrompt(template: RuntimeTemplateId = "react-spa"): string {
  const scaffold = RUNTIME_TEMPLATES[template];
  return `You write complete React applications. Return one JSON object and nothing else — no prose, no markdown fence.

SHAPE
{
  "schemaVersion": "${APP_SCHEMA_VERSION}",
  "metadata": { "name": string, "description": string, "locale": string },
  "runtime": { "template": "${template}", "dependencies": string[] },
  "routes": [{ "path": "/", "module": "src/App.tsx", "title": string }],
  "files": { "<path>": "<file contents>" }
}

WHAT YOU OWN
The component tree, the file structure, the state, the interactions, the
layout, the typography and the colour system. Build the application the brief
describes. There is no page template and no section vocabulary to fill in —
two different briefs should produce two applications with nothing structural
in common.

Build a real application, not a description of one. If the brief implies
filtering, filtering must work. If it implies a form, the form must validate
and respond. Client-side state, derived values, conditional rendering, modals,
tabs, keyboard handling — all of it is available and all of it is expected.

FILES
- ${scaffold.root} must exist and default-export the root component.
- ${scaffold.entry} is written by Ventrio. Do not supply it.
- Paths start with ${ALLOWED_PATH_ROOTS.join(" or ")} and end with ${ALLOWED_EXTENSIONS.join(", ")}.
- Any structure you like inside those roots. Nested component folders are
  encouraged; one enormous file is not.
- These are generated by Ventrio and will be refused: ${RESERVED_PATHS.join(", ")}.
- Import a stylesheet the normal way (\`import "./styles.css"\`).

LIBRARIES — these and only these
${describeRuntime()}
Declare in \`runtime.dependencies\` exactly what you import. You cannot install
anything: there is no package manager, no CDN and no network.

THE ENVIRONMENT IS SEALED
The app runs in a sandboxed frame with no network and no storage. These are
not discouraged, they are unavailable, and using them fails the build:
fetch, XMLHttpRequest, WebSocket, EventSource, sendBeacon, localStorage,
sessionStorage, indexedDB, document.cookie, eval, new Function, import.meta,
window.parent / top / opener, service workers, require().

Hold everything in React state. Put any data the app needs in a source file
and import it.

BUDGETS
Up to ${APP_BUDGETS.maxFiles} files, ${Math.round(APP_BUDGETS.maxFileBytes / 1000)} kB per file,
${Math.round(APP_BUDGETS.maxTotalSourceBytes / 1000)} kB total, ${APP_BUDGETS.maxRoutes} routes.

QUALITY
- Mobile first. Nothing may overflow horizontally at 390px.
- Type at a readable measure. A body column narrower than about 40 characters
  is a bug, not a style.
- One structural idea carried consistently beats five decorations.
- Real states: empty, selected, invalid, submitted. A control that does
  nothing is worse than a control that is absent.
- Label controls, and keep keyboard users in mind — a modal needs a way out.`;
}

export function appUserPrompt(brief: string): string {
  return `${brief}\n\nReturn the JSON object now.`;
}

/**
 * The repair prompt.
 *
 * It carries the exact diagnostics and asks for a patch rather than a rewrite.
 * A repair that returns a whole new project throws away everything that was
 * already right, and the failure list is usually three lines long.
 */
export function appRepairPrompt(diagnostics: string[]): string {
  return `The project you returned was refused. Fix exactly these problems and change nothing else.

${diagnostics.map((line) => `- ${line}`).join("\n")}

Return a patch, not a whole project:
{
  "schemaVersion": "${PATCH_SCHEMA_VERSION}",
  "summary": "<one line>",
  "write": { "<path>": "<complete new contents of that file>" },
  "remove": ["<path>"]
}

Include the complete contents of each file you change. Files you do not
mention are kept as they are.`;
}
