/**
 * What the model is told, generated from the gate's own constants.
 *
 * Every list here is derived rather than hand-written. A prompt that advertises
 * a library the allowlist refuses, or omits one it permits, costs a paid
 * request to discover — the codegen canary lost three generations to exactly
 * this class of drift between what was asked for and what was accepted.
 *
 * The prompt describes a contract and a set of capabilities. It does not
 * describe a product, a page, a set of sections or a layout, because the entire
 * point of replacing the page schema was to stop doing that. What to build is
 * the brief's business; how to structure it is the model's.
 */

import { ALLOWED_EXTENSIONS, ALLOWED_PATH_ROOTS, APP_BUDGETS, APP_SCHEMA_VERSION, RESERVED_PATHS } from "./contract";
import { PATCH_SCHEMA_VERSION } from "./edit";
import { describeRuntime, RUNTIME_TEMPLATES, type RuntimeTemplateId } from "./runtime";

export function appSystemPrompt(template: RuntimeTemplateId = "react-spa"): string {
  const scaffold = RUNTIME_TEMPLATES[template];
  return `You write complete React applications. Return one JSON object and nothing else — no prose, no markdown fence.

SHAPE
{
  "schemaVersion": "${APP_SCHEMA_VERSION}",
  "metadata": { "name": string, "description": string, "locale": string },
  "runtime": { "template": "${template}", "dependencies": string[] },
  "routes": [{ "path": "/", "module": "src/App.tsx", "title": string }],
  "files": { "<path>": "<file contents>" }
}

WHAT YOU OWN
The component tree, the file structure, the state, the interactions, the
layout, the typography and the colour system. Build the application the brief
describes. There is no page template and no section vocabulary to fill in —
two different briefs should produce two applications with nothing structural
in common.

Build a real application, not a description of one. If the brief implies
filtering, filtering must work. If it implies a form, the form must validate
and respond. Client-side state, derived values, conditional rendering, modals,
tabs, keyboard handling — all of it is available and all of it is expected.

FILES
- ${scaffold.root} must exist and default-export the root component.
- ${scaffold.entry} is written by Ventrio. Do not supply it.
- Paths start with ${ALLOWED_PATH_ROOTS.join(" or ")} and end with ${ALLOWED_EXTENSIONS.join(", ")}.
- Any structure you like inside those roots. Nested component folders are
  encouraged; one enormous file is not.
- These are generated by Ventrio and will be refused: ${RESERVED_PATHS.join(", ")}.
- Import a stylesheet the normal way (\`import "./styles.css"\`).

LIBRARIES — these and only these
${describeRuntime()}
Declare in \`runtime.dependencies\` exactly what you import. You cannot install
anything: there is no package manager, no CDN and no network.

THE ENVIRONMENT IS SEALED
The app runs in a sandboxed frame with no network and no storage. These are
not discouraged, they are unavailable, and using even one of them fails the
build outright — the project is refused, not degraded:
fetch, XMLHttpRequest, WebSocket, EventSource, sendBeacon, localStorage,
sessionStorage, indexedDB, document.cookie, eval, new Function, import.meta,
window.parent / top / opener, service workers, require().

That includes a "persistence" or "storage" helper module. A generated project
was refused for one src/utils/storage.ts wrapping localStorage; everything
else about it was fine. There is no persistence layer to write.

Hold everything in React state — useState, useReducer, context. Seed it from
a source file you import. State resets when the preview reloads, and that is
the expected behaviour, not a bug to work around.

WHAT TO BUILD, AND WHEN
Build what was asked for. If the brief describes an application, build the
working application. If it asks for a landing page or a marketing page, build
that page. If it is ambiguous but describes something people use, build the
application.

Never substitute a marketing page, a waitlist, a signup mock or an
explanation of what the product could become for the functionality that was
requested. A page describing the tool is not the tool.

FORMS
Every form validates before it submits. Required fields are enforced, invalid
values are refused with a message next to the field that caused it, and a
successful submission visibly confirms itself — the new item appears, or the
form reports what it did. A form that accepts an empty submit silently is a
defect, and a generated app shipped with exactly that.

BUDGETS
Up to ${APP_BUDGETS.maxFiles} files, ${Math.round(APP_BUDGETS.maxFileBytes / 1000)} kB per file,
${Math.round(APP_BUDGETS.maxTotalSourceBytes / 1000)} kB total, ${APP_BUDGETS.maxRoutes} routes.

QUALITY
- Mobile first. Nothing may overflow horizontally at 390px.
- Type at a readable measure. A body column narrower than about 40 characters
  is a bug, not a style.
- One structural idea carried consistently beats five decorations.
- Real states: empty, selected, invalid, submitted. A control that does
  nothing is worse than a control that is absent.
- Label controls, and keep keyboard users in mind — a modal needs a way out.`;
}

export function appUserPrompt(brief: string): string {
  return `${brief}\n\nReturn the JSON object now.`;
}

/**
 * What the model is shown of the project it is being asked to repair.
 *
 * A patch is a diff against a base, and the request that carries it is a fresh
 * single-turn call: the model has no memory of what it returned a minute ago.
 * Asking for a patch without stating the base is asking it to edit a file it
 * cannot see, so the context is a required argument rather than an optional
 * one — the type is the check.
 */
export interface AppRepairContext {
  /** Every path in the project, so a patch never re-invents a file that exists. */
  manifest: string[];
  /** Complete current contents of the files the patch is expected to touch. */
  files: Record<string, string>;
  /** True when `files` is a subset — the prompt then says so explicitly. */
  partial: boolean;
}

/**
 * The repair prompt.
 *
 * It carries the exact diagnostics and asks for a patch rather than a rewrite.
 * A repair that returns a whole new project throws away everything that was
 * already right, and the failure list is usually three lines long.
 *
 * When only some files are shown, the prompt says so in as many words. A model
 * shown four of eleven files and not told the rest exist rewrites them from
 * memory, and a patch that "restores" nine files it never saw is exactly the
 * whole-project regeneration this path exists to avoid.
 */
export function appRepairPrompt(diagnostics: string[], context: AppRepairContext): string {
  const shown = Object.entries(context.files)
    .map(([path, contents]) => `--- ${path} ---\n${contents}\n--- end ${path} ---`)
    .join("\n\n");

  return `The project you returned was refused. Fix exactly these problems and change nothing else.

${diagnostics.map((line) => `- ${line}`).join("\n")}

THE PROJECT AS IT STANDS
${context.manifest.map((path) => `- ${path}`).join("\n")}
${context.partial
    ? "\nOnly the files below are reproduced. Every other file above is unchanged\nand will be kept — do not rewrite one from memory.\n"
    : ""}
${shown}

Return a patch, not a whole project:
{
  "schemaVersion": "${PATCH_SCHEMA_VERSION}",
  "summary": "<one line>",
  "write": { "<path>": "<complete new contents of that file>" },
  "remove": ["<path>"]
}

Include the complete contents of each file you change. Files you do not
mention are kept as they are.

The environment has not changed: no localStorage, sessionStorage, indexedDB,
cookies, service workers, fetch or eval. Hold state in React. Do not fix a
problem by replacing working functionality with a simpler page.`;
}

/**
 * The other repair: start again, with the failures attached.
 *
 * Used when there is no base to patch — the response was not JSON, or it was
 * refused by validation, and in neither case does a project exist that
 * `applyPatch` could be applied to. The brief is restated because this is a
 * fresh single-turn request and the model has not seen it since.
 *
 * The refused project is not echoed back. It can be 300 kB, the failure list
 * already says what was wrong with it, and returning a refused document invites
 * a patch around the rule rather than compliance with it.
 */
export function appRewritePrompt(brief: string, diagnostics: string[]): string {
  return `${brief}

YOUR PREVIOUS PROJECT WAS REFUSED. Fix every point below and return the whole
project again as a single JSON object.

${diagnostics.slice(0, 25).map((line) => `- ${line}`).join("\n")}

Build the same product the brief asked for. Fixing a refusal by shipping less
than was requested — a marketing page instead of the application, a form
without validation — is not a fix.`;
}
