/**
 * The document a generated application runs inside.
 *
 * WHY `srcdoc` IS SUFFICIENT HERE, decided from the constraint rather than
 * convenience. The requirement is an origin the generated code cannot use to
 * reach Ventrio. An iframe carrying `sandbox="allow-scripts"` *without*
 * `allow-same-origin` is assigned an opaque origin: `document.domain` is null,
 * `localStorage` and `document.cookie` throw, and every same-origin check
 * against the embedder fails. Scripts run; nothing they can call reaches out.
 *
 * The combination that would break this is `allow-scripts allow-same-origin`
 * together, because that returns the frame to the embedder's origin and the
 * sandbox becomes decoration. `SANDBOX_TOKENS` below therefore omits
 * `allow-same-origin` permanently, and the sandbox test asserts the pair never
 * appears — this is the single most important line in the file.
 *
 * A separate preview *origin* would add one thing this does not have: isolation
 * from other generated apps under a shared storage partition. Since storage is
 * unavailable in an opaque origin at all, there is nothing to partition, and a
 * second origin would mean serving generated bytes from a URL — a fetchable,
 * linkable, indexable address for code a model wrote. `srcdoc` has no address.
 * That is a stronger property, so it is the one kept. If a future requirement
 * needs persistent storage or a service worker inside a generated app, that
 * trade reverses and a dedicated origin becomes correct; the note is here so
 * the decision is re-made rather than inherited.
 *
 * The CSP below is the second, independent layer. It holds even if the sandbox
 * attribute is weakened by a careless edit, and vice versa.
 */

import { RUNTIME_LIBRARIES } from "./runtime";
import { PREVIEW_PROTOCOL_VERSION, PREVIEW_SOURCE } from "./protocol";

/**
 * The sandbox attribute. `allow-same-origin` is absent by design.
 *
 * - allow-scripts: the whole point; a generated app is a program.
 * - allow-forms: forms may submit to themselves and be handled in JS. Without
 *   it a submit handler never fires and every generated form looks broken.
 * - allow-popups is NOT granted: nothing generated should open a window.
 * - allow-modals is NOT granted: alert() blocks the embedder's event loop.
 * - allow-top-navigation is NOT granted: a generated app cannot move the tab.
 */
export const SANDBOX_TOKENS = ["allow-scripts", "allow-forms"] as const;

export const SANDBOX_ATTRIBUTE = SANDBOX_TOKENS.join(" ");

/**
 * The policy inside the generated document.
 *
 * `script-src` must permit inline and blob: the app is delivered as an inline
 * module and the import map resolves libraries to blob URLs built in-document.
 * There is no nonce available — `srcdoc` inherits nothing from the embedder's
 * per-request nonce — so the containment for scripts is the opaque origin and
 * the absence of any network destination, not script-src.
 *
 * Everything that could reach the network is `'none'`. That is what makes
 * "network denied by default" true rather than aspirational: connect-src none
 * kills fetch, XHR, WebSocket, EventSource and sendBeacon at the platform
 * level, whatever the source passed the validator.
 */
export function innerCsp(): string {
  return [
    "default-src 'none'",
    // Inline module + blob: for the import-map shims. No remote script.
    "script-src 'unsafe-inline' blob:",
    "style-src 'unsafe-inline'",
    // Only Ventrio-owned assets, which arrive as data URIs.
    "img-src data:",
    "font-src data:",
    // The four that matter: no network of any kind, from anywhere.
    "connect-src 'none'",
    "media-src 'none'",
    "object-src 'none'",
    "frame-src 'none'",
    "worker-src 'none'",
    "form-action 'none'",
    "base-uri 'none'",
    // `frame-ancestors` is deliberately absent: a <meta> CSP cannot deliver it
    // and Chrome logs a warning for every preview if you try. Embedding is
    // controlled by the sandbox attribute and by Ventrio's own response
    // headers, which is where that directive belongs.
  ].join("; ");
}

export interface SandboxInput {
  /** The compiled ES module for the generated app. */
  code: string;
  /** The compiled stylesheet, if the project imported one. */
  css?: string;
  /** The single runtime graph, exporting `__libs`. Ventrio-owned. */
  runtimeCore: string;
  /** Specifier → its named exports, used to build the facades. */
  runtimeNames: Record<string, string[]>;
  lang: string;
  title: string;
  /** Ventrio-owned asset id → data URI. */
  assets?: Record<string, string>;
  /**
   * The current request's CSP nonce, applied to Ventrio's own script tags.
   *
   * A `srcdoc` frame inherits the embedding page's Content-Security-Policy,
   * and Ventrio's pages allow scripts only by nonce. Without this the document
   * loads, the stylesheet applies, and React never mounts — the frame renders
   * styled and empty, which is exactly what staging showed.
   *
   * It is per-request and ephemeral: passed in at build time, never stored on
   * the project and never part of `GeneratedAppV1`. The document is rebuilt on
   * every read, so each render carries that request's nonce and no other.
   *
   * Applied ONLY to the three tags this function writes. Markup the model
   * produced never receives it, so a generated `<script>` in the app's own
   * output is still refused by the inherited policy.
   */
  nonce?: string;
}

/**
 * A nonce is written into an HTML attribute, so it is checked rather than
 * trusted. The middleware emits base64 of a UUID; anything outside that
 * alphabet is dropped rather than escaped, because a nonce that needed
 * escaping did not come from the middleware.
 */
function nonceAttribute(nonce: string | undefined): string {
  if (!nonce || !/^[A-Za-z0-9+/_=-]{16,256}$/.test(nonce)) return "";
  return ` nonce="${nonce}"`;
}

const escapeHtml = (value: string): string =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");

/**
 * Refuses a payload that could close its own script element.
 *
 * The compiled bundle goes inside `<script type="module">`, and `</script>`
 * anywhere in it — including inside a string literal — ends the element and
 * turns everything after it into markup. esbuild does not escape this for us
 * because it has no idea where its output is going.
 */
export function escapeForScript(code: string): string {
  return code.replace(/<\/(script)/gi, "<\\/$1");
}

/**
 * The same rule for the stylesheet.
 *
 * A `</style>` inside generated CSS — in a content property, say — would close
 * the element and turn the rest of the sheet into markup. Escaped rather than
 * refused because the sequence has a legitimate, if rare, use.
 */
export function escapeForStyle(css: string): string {
  return css.replace(/<\/(style)/gi, "<\\/$1");
}

/**
 * Assembles the complete document.
 *
 * Order is load-bearing: the CSP `<meta>` is the first element in `<head>`,
 * before the import map and before any code. A policy declared after the thing
 * it governs is applied after that thing has already had its chance.
 */
/**
 * The origin relative paths are resolved against inside the sandbox.
 *
 * `.invalid` is reserved by RFC 2606 and can never resolve to a host. Together
 * with `connect-src 'none'` — which denies fetch, XHR, WebSocket, EventSource
 * and sendBeacon at the platform level — this is a parsing device and not a
 * destination. It grants a generated app no reach it did not already have.
 */
export const SANDBOX_BASE_URL = "https://app.ventrio.invalid/";

/**
 * A base URL that relative paths can actually be resolved against.
 *
 * THE DEFECT THIS CLOSES. The document's URL is `about:srcdoc` and its origin is
 * opaque, which serialises as the string `"null"`. Both are *cannot-be-a-base*
 * URLs, so every one of these throws, in every browser:
 *
 *     new URL("/")                        // no base at all
 *     new URL("/", "about:srcdoc")        // location.href
 *     new URL("/", "null")                // window.origin, location.origin
 *     new URL("/", "")                    // origin on some engines
 *
 * That is not hypothetical. Chrome reports it as
 * `TypeError: Failed to construct 'URL': Invalid URL` and WebKit as
 * `TypeError: "/" cannot be parsed as a URL` — the second is what a beta user on
 * iOS saw, with a blank frame behind it. It reached them because react-router
 * resolves against `location.origin || location.href` and calls that during
 * *render*, so a single `<Link to="/">` was enough to blank the app on first
 * paint. `RUNTIME_OVERRIDES` fixes that library; this fixes the document, so
 * that a generated app calling `new URL("/settings")` in its own code — which
 * the product promises it may — also works.
 *
 * THE RULE. When the base is one this document cannot resolve against, and the
 * input is not already absolute, resolve against `SANDBOX_BASE_URL` instead.
 * Anything with a usable base, and any absolute URL, takes the native path
 * untouched. A genuinely malformed URL still throws: a shim that swallowed
 * everything would hide real bugs in generated code.
 *
 * Subclassing rather than wrapping is deliberate: `class extends URL` keeps
 * `instanceof`, and keeps the statics — `createObjectURL`, `revokeObjectURL`,
 * `canParse`, `parse` — reachable through the prototype chain. The import-map
 * shim that runs next depends on `URL.createObjectURL` and must not notice that
 * anything changed.
 *
 * The whole body is inside a try/catch: a browser that dislikes any part of this
 * keeps its native `URL` rather than losing the document.
 *
 * Exported so `preview-base-url.test.mts` can evaluate the real script rather
 * than a re-typed copy of it — a test against a paraphrase proves nothing about
 * what ships.
 */
export const BASE_URL_BOOTSTRAP = `(function () {
  var BASE = ${JSON.stringify(SANDBOX_BASE_URL)};
  try {
    var Native = URL;
    var unusable = function (base) {
      if (base === undefined || base === null) return true;
      var text = String(base);
      // "" and "null" are what an opaque origin reports for its origin;
      // "about:*" is this document's own URL. None can have a path resolved
      // against it.
      return text === "" || text === "null" || text.slice(0, 6) === "about:";
    };
    var Patched = class extends Native {
      constructor(url, base) {
        if (unusable(base)) {
          var text = String(url);
          // Already absolute? Then it needs no base and must keep its own.
          var absolute = Native.canParse ? Native.canParse(text) : (function () {
            try { new Native(text); return true; } catch (ignored) { return false; }
          })();
          super(text, absolute ? undefined : BASE);
          return;
        }
        super(url, base);
      }
    };
    globalThis.URL = Patched;
    if (typeof globalThis.webkitURL !== "undefined") globalThis.webkitURL = Patched;
  } catch (ignored) { /* the native URL stays; nothing here is worth a blank frame */ }
})();`;

export function buildSandboxDocument(input: SandboxInput): string {
  const lang = /^[a-zA-Z-]{2,16}$/.test(input.lang) ? input.lang : "en";

  /**
   * The import map, built in-document from Ventrio's own bytes.
   *
   * The runtime is one compiled graph — React exists in it exactly once — and
   * each bare specifier gets a small facade module that re-exports that
   * library's namespace with static named exports. The facades have to be built
   * here rather than server-side because they import the core by its blob URL,
   * which does not exist until this code runs.
   *
   * The merge in each facade is not incidental. esbuild's CommonJS interop
   * surfaces only the names its lexer could find, so for a package whose entry
   * is a bare `module.exports = require(...)` the namespace carries just
   * `default`. Merging default-first, namespace-second recovers the real
   * exports for CommonJS while letting a true ES module's named exports win.
   */
  const shim = `const __core = URL.createObjectURL(new Blob([${JSON.stringify(input.runtimeCore)}], { type: "text/javascript" }));
const __names = ${JSON.stringify(input.runtimeNames)};
const __imports = { "ventrio:runtime": __core };
for (const spec of Object.keys(__names)) {
  const list = __names[spec];
  const src = 'import { __libs } from ' + JSON.stringify(__core) + ';\\n'
    + 'const __ns = __libs[' + JSON.stringify(spec) + '];\\n'
    + 'const __src = Object.assign({}, (__ns && typeof __ns.default === "object" ? __ns.default : null), __ns);\\n'
    + (list.length ? 'const { ' + list.join(", ") + ' } = __src;\\nexport { ' + list.join(", ") + ' };\\n' : '')
    + 'export default (__ns && "default" in __ns) ? __ns.default : __src;\\n';
  __imports[spec] = URL.createObjectURL(new Blob([src], { type: "text/javascript" }));
}
const im = document.createElement("script");
im.type = "importmap";
im.textContent = JSON.stringify({ imports: __imports });
document.head.appendChild(im);`;

  /**
   * The failure reporter, and why it is a classic script before the module.
   *
   * `ready` and `runtime-error` used to be posted by the app's own compiled
   * entry — inside the very module that can fail to load. When a bare specifier
   * did not resolve, the whole graph died before its first line: the parent got
   * no ready, no error, and no way to tell a slow build from a dead one. The
   * preview simply stayed white, for as long as anyone left it open.
   *
   * This runs first, in its own script, so it is already listening when the
   * module is fetched. It reports three things the module cannot report about
   * itself — a load or resolution error, an unhandled rejection, and a start
   * that never happened — using the same envelope the parser already checks, so
   * nothing about the message contract changes.
   *
   * The watchdog is the backstop: any failure mode nobody predicted still ends
   * as a stated error rather than a blank rectangle. It is cancelled by the
   * app's own `ready`, so a healthy app never sees it.
   */
  const reporter = `(function () {
  var sent = 0;
  var started = false;
  function post(kind, message, stack) {
    if (sent > 8) return;
    sent += 1;
    try {
      parent.postMessage({
        source: ${JSON.stringify(PREVIEW_SOURCE)},
        version: ${PREVIEW_PROTOCOL_VERSION},
        type: "runtime-error",
        payload: {
          kind: String(kind).slice(0, 40),
          message: String(message == null ? "Unknown error" : message).slice(0, 2000),
          stack: String(stack == null ? "" : stack).slice(0, 4000)
        }
      }, "*");
    } catch (ignored) {}
  }
  addEventListener("message", function (event) {
    // The app's own ready passes through here on its way out; seeing it is how
    // the watchdog knows it has nothing to say.
    if (event && event.data && event.data.type === "ready") started = true;
  });
  addEventListener("error", function (event) {
    var error = event && event.error;
    post(error && error.name ? error.name : "Error", (error && error.message) || (event && event.message), error && error.stack);
  }, true);
  addEventListener("unhandledrejection", function (event) {
    var reason = event && event.reason;
    post("UnhandledRejection", (reason && reason.message) || reason, reason && reason.stack);
  });
  var mark = function () { started = true; };
  window.__ventrioStarted = mark;
  setTimeout(function () {
    if (started || window.__ventrioReady) return;
    var root = document.getElementById("root");
    if (root && root.childElementCount > 0) return;
    post("DidNotStart", "The application did not start. Its code loaded but nothing rendered.", "");
  }, 8000);
})();`;

  const nonce = nonceAttribute(input.nonce);
  const assets = input.assets && Object.keys(input.assets).length > 0
    ? `<script${nonce}>window.__ventrioAssets = ${JSON.stringify(input.assets)};</script>`
    : "";

  return `<!doctype html><html lang="${escapeHtml(lang)}"><head>`
    + `<meta http-equiv="Content-Security-Policy" content="${escapeHtml(innerCsp())}">`
    + `<meta charset="utf-8">`
    + `<meta name="viewport" content="width=device-width, initial-scale=1">`
    + `<title>${escapeHtml(input.title)}</title>`
    /**
     * The mobile safety floor, applied to every generated application.
     *
     * WHY `html` AND NOT JUST `body`. A real iPhone could drag a published app
     * sideways while desktop was fine. `overflow-x: hidden` was set on `body`
     * alone, which the spec propagates to the viewport — but propagation makes
     * the body's own overflow `visible` again, and WebKit will still touch-pan
     * the document when something genuinely sticks out. Setting it on both, plus
     * a hard `max-width`, is what actually pins the page on iOS.
     *
     * WHAT THIS DELIBERATELY DOES NOT DO. It does not touch inner scrollers. A
     * child with `overflow-x: auto` — the wrapper a model puts around a wide
     * table, and both apps measured had one — keeps its own scrollbar, because
     * the wrapper itself fits and only its contents overflow. So a table that is
     * *meant* to scroll sideways still does; only the page cannot.
     *
     * Content wide by accident is clipped rather than dragging the page. That is
     * a real trade and the better half of it: a layout that pushes the viewport
     * sideways is unusable on a phone either way, and clipping keeps the primary
     * column readable and the controls reachable.
     *
     * `overflow-wrap` is here for the other common cause: one long unbroken
     * string — a URL, an id, a hash — is enough to widen a whole page.
     */
    + `<style>*,*::before,*::after{box-sizing:border-box}html,body{margin:0;padding:0}`
    + `html{overflow-x:hidden}`
    + `body{min-height:100vh;max-width:100%;overflow-x:hidden;-webkit-text-size-adjust:100%;overflow-wrap:break-word}`
    + `img,svg,video,canvas{max-width:100%;height:auto}img{display:block}`
    + `#root{min-height:100vh;max-width:100%;overflow-x:hidden}</style>`
    // The generated app's own stylesheet, after the reset so it wins, and
    // inside a <style> element whose contents cannot close it — the same rule
    // the script payload follows.
    + (input.css ? `<style>${escapeForStyle(input.css)}</style>` : "")
    + `</head><body><div id="root"></div>`
    + assets
    // Before everything, because the import-map shim on the third line calls
    // URL.createObjectURL and the app module resolves paths. It cannot throw:
    // its whole body is inside a try/catch that falls back to the native URL.
    + `<script${nonce}>${escapeForScript(BASE_URL_BOOTSTRAP)}</script>`
    // Then the reporter, so it is listening before anything can fail.
    + `<script${nonce}>${escapeForScript(reporter)}</script>`
    + `<script${nonce}>${escapeForScript(shim)}</script>`
    + `<script type="module"${nonce}>${escapeForScript(input.code)}</script>`
    + `</body></html>`;
}

/** Names the runtime is expected to supply, so a missing one is caught early. */
export const REQUIRED_LIBRARY_NAMES: readonly string[] = RUNTIME_LIBRARIES.map((l) => l.name);
