/**
 * The document a generated application runs inside.
 *
 * WHY `srcdoc` IS SUFFICIENT HERE, decided from the constraint rather than
 * convenience. The requirement is an origin the generated code cannot use to
 * reach Ventrio. An iframe carrying `sandbox="allow-scripts"` *without*
 * `allow-same-origin` is assigned an opaque origin: `document.domain` is null,
 * `localStorage` and `document.cookie` throw, and every same-origin check
 * against the embedder fails. Scripts run; nothing they can call reaches out.
 *
 * The combination that would break this is `allow-scripts allow-same-origin`
 * together, because that returns the frame to the embedder's origin and the
 * sandbox becomes decoration. `SANDBOX_TOKENS` below therefore omits
 * `allow-same-origin` permanently, and the sandbox test asserts the pair never
 * appears — this is the single most important line in the file.
 *
 * A separate preview *origin* would add one thing this does not have: isolation
 * from other generated apps under a shared storage partition. Since storage is
 * unavailable in an opaque origin at all, there is nothing to partition, and a
 * second origin would mean serving generated bytes from a URL — a fetchable,
 * linkable, indexable address for code a model wrote. `srcdoc` has no address.
 * That is a stronger property, so it is the one kept. If a future requirement
 * needs persistent storage or a service worker inside a generated app, that
 * trade reverses and a dedicated origin becomes correct; the note is here so
 * the decision is re-made rather than inherited.
 *
 * The CSP below is the second, independent layer. It holds even if the sandbox
 * attribute is weakened by a careless edit, and vice versa.
 */

import { RUNTIME_LIBRARIES } from "./runtime";

/**
 * The sandbox attribute. `allow-same-origin` is absent by design.
 *
 * - allow-scripts: the whole point; a generated app is a program.
 * - allow-forms: forms may submit to themselves and be handled in JS. Without
 *   it a submit handler never fires and every generated form looks broken.
 * - allow-popups is NOT granted: nothing generated should open a window.
 * - allow-modals is NOT granted: alert() blocks the embedder's event loop.
 * - allow-top-navigation is NOT granted: a generated app cannot move the tab.
 */
export const SANDBOX_TOKENS = ["allow-scripts", "allow-forms"] as const;

export const SANDBOX_ATTRIBUTE = SANDBOX_TOKENS.join(" ");

/**
 * The policy inside the generated document.
 *
 * `script-src` must permit inline and blob: the app is delivered as an inline
 * module and the import map resolves libraries to blob URLs built in-document.
 * There is no nonce available — `srcdoc` inherits nothing from the embedder's
 * per-request nonce — so the containment for scripts is the opaque origin and
 * the absence of any network destination, not script-src.
 *
 * Everything that could reach the network is `'none'`. That is what makes
 * "network denied by default" true rather than aspirational: connect-src none
 * kills fetch, XHR, WebSocket, EventSource and sendBeacon at the platform
 * level, whatever the source passed the validator.
 */
export function innerCsp(): string {
  return [
    "default-src 'none'",
    // Inline module + blob: for the import-map shims. No remote script.
    "script-src 'unsafe-inline' blob:",
    "style-src 'unsafe-inline'",
    // Only Ventrio-owned assets, which arrive as data URIs.
    "img-src data:",
    "font-src data:",
    // The four that matter: no network of any kind, from anywhere.
    "connect-src 'none'",
    "media-src 'none'",
    "object-src 'none'",
    "frame-src 'none'",
    "worker-src 'none'",
    "form-action 'none'",
    "base-uri 'none'",
    // `frame-ancestors` is deliberately absent: a <meta> CSP cannot deliver it
    // and Chrome logs a warning for every preview if you try. Embedding is
    // controlled by the sandbox attribute and by Ventrio's own response
    // headers, which is where that directive belongs.
  ].join("; ");
}

export interface SandboxInput {
  /** The compiled ES module for the generated app. */
  code: string;
  /** The compiled stylesheet, if the project imported one. */
  css?: string;
  /** The single runtime graph, exporting `__libs`. Ventrio-owned. */
  runtimeCore: string;
  /** Specifier → its named exports, used to build the facades. */
  runtimeNames: Record<string, string[]>;
  lang: string;
  title: string;
  /** Ventrio-owned asset id → data URI. */
  assets?: Record<string, string>;
  /**
   * The current request's CSP nonce, applied to Ventrio's own script tags.
   *
   * A `srcdoc` frame inherits the embedding page's Content-Security-Policy,
   * and Ventrio's pages allow scripts only by nonce. Without this the document
   * loads, the stylesheet applies, and React never mounts — the frame renders
   * styled and empty, which is exactly what staging showed.
   *
   * It is per-request and ephemeral: passed in at build time, never stored on
   * the project and never part of `GeneratedAppV1`. The document is rebuilt on
   * every read, so each render carries that request's nonce and no other.
   *
   * Applied ONLY to the three tags this function writes. Markup the model
   * produced never receives it, so a generated `<script>` in the app's own
   * output is still refused by the inherited policy.
   */
  nonce?: string;
}

/**
 * A nonce is written into an HTML attribute, so it is checked rather than
 * trusted. The middleware emits base64 of a UUID; anything outside that
 * alphabet is dropped rather than escaped, because a nonce that needed
 * escaping did not come from the middleware.
 */
function nonceAttribute(nonce: string | undefined): string {
  if (!nonce || !/^[A-Za-z0-9+/_=-]{16,256}$/.test(nonce)) return "";
  return ` nonce="${nonce}"`;
}

const escapeHtml = (value: string): string =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");

/**
 * Refuses a payload that could close its own script element.
 *
 * The compiled bundle goes inside `<script type="module">`, and `</script>`
 * anywhere in it — including inside a string literal — ends the element and
 * turns everything after it into markup. esbuild does not escape this for us
 * because it has no idea where its output is going.
 */
export function escapeForScript(code: string): string {
  return code.replace(/<\/(script)/gi, "<\\/$1");
}

/**
 * The same rule for the stylesheet.
 *
 * A `</style>` inside generated CSS — in a content property, say — would close
 * the element and turn the rest of the sheet into markup. Escaped rather than
 * refused because the sequence has a legitimate, if rare, use.
 */
export function escapeForStyle(css: string): string {
  return css.replace(/<\/(style)/gi, "<\\/$1");
}

/**
 * Assembles the complete document.
 *
 * Order is load-bearing: the CSP `<meta>` is the first element in `<head>`,
 * before the import map and before any code. A policy declared after the thing
 * it governs is applied after that thing has already had its chance.
 */
export function buildSandboxDocument(input: SandboxInput): string {
  const lang = /^[a-zA-Z-]{2,16}$/.test(input.lang) ? input.lang : "en";

  /**
   * The import map, built in-document from Ventrio's own bytes.
   *
   * The runtime is one compiled graph — React exists in it exactly once — and
   * each bare specifier gets a small facade module that re-exports that
   * library's namespace with static named exports. The facades have to be built
   * here rather than server-side because they import the core by its blob URL,
   * which does not exist until this code runs.
   *
   * The merge in each facade is not incidental. esbuild's CommonJS interop
   * surfaces only the names its lexer could find, so for a package whose entry
   * is a bare `module.exports = require(...)` the namespace carries just
   * `default`. Merging default-first, namespace-second recovers the real
   * exports for CommonJS while letting a true ES module's named exports win.
   */
  const shim = `const __core = URL.createObjectURL(new Blob([${JSON.stringify(input.runtimeCore)}], { type: "text/javascript" }));
const __names = ${JSON.stringify(input.runtimeNames)};
const __imports = { "ventrio:runtime": __core };
for (const spec of Object.keys(__names)) {
  const list = __names[spec];
  const src = 'import { __libs } from ' + JSON.stringify(__core) + ';\\n'
    + 'const __ns = __libs[' + JSON.stringify(spec) + '];\\n'
    + 'const __src = Object.assign({}, (__ns && typeof __ns.default === "object" ? __ns.default : null), __ns);\\n'
    + (list.length ? 'const { ' + list.join(", ") + ' } = __src;\\nexport { ' + list.join(", ") + ' };\\n' : '')
    + 'export default (__ns && "default" in __ns) ? __ns.default : __src;\\n';
  __imports[spec] = URL.createObjectURL(new Blob([src], { type: "text/javascript" }));
}
const im = document.createElement("script");
im.type = "importmap";
im.textContent = JSON.stringify({ imports: __imports });
document.head.appendChild(im);`;

  const nonce = nonceAttribute(input.nonce);
  const assets = input.assets && Object.keys(input.assets).length > 0
    ? `<script${nonce}>window.__ventrioAssets = ${JSON.stringify(input.assets)};</script>`
    : "";

  return `<!doctype html><html lang="${escapeHtml(lang)}"><head>`
    + `<meta http-equiv="Content-Security-Policy" content="${escapeHtml(innerCsp())}">`
    + `<meta charset="utf-8">`
    + `<meta name="viewport" content="width=device-width, initial-scale=1">`
    + `<title>${escapeHtml(input.title)}</title>`
    + `<style>*,*::before,*::after{box-sizing:border-box}html,body{margin:0;padding:0}`
    + `body{min-height:100vh;overflow-x:hidden;-webkit-text-size-adjust:100%}`
    + `img{max-width:100%;height:auto;display:block}#root{min-height:100vh}</style>`
    // The generated app's own stylesheet, after the reset so it wins, and
    // inside a <style> element whose contents cannot close it — the same rule
    // the script payload follows.
    + (input.css ? `<style>${escapeForStyle(input.css)}</style>` : "")
    + `</head><body><div id="root"></div>`
    + assets
    + `<script${nonce}>${escapeForScript(shim)}</script>`
    + `<script type="module"${nonce}>${escapeForScript(input.code)}</script>`
    + `</body></html>`;
}

/** Names the runtime is expected to supply, so a missing one is caught early. */
export const REQUIRED_LIBRARY_NAMES: readonly string[] = RUNTIME_LIBRARIES.map((l) => l.name);
