import type { Locale } from "@/i18n/locale";

export const OUTPUT_COPY = {
  en: {
    identityLabel: "Identity",
    targetUserLabel: "For",
    primaryValueLabel: "Primary value",
    mainActionLabel: "Take action",
    selectPlaceholder: "Choose an option",
    launchCopyLabel: "Launch copy",
    previewConfirmation: "Preview only. Publish this version to collect real responses.",
    madeWith: "Made with Ventrio",
    acceptedCommunity: "You're in.",
    acceptedService: "Thanks — your response was sent.",
    acceptedContent: "You're on the list.",
    acceptedProduct: "You're on the list.",
    invalid: "Check the highlighted fields and try again.",
    rateLimited: "You've sent a few responses already. Please try again later.",
    unavailable: "This form is briefly unavailable. Please try again.",
    submitting: "Sending…",
  },
  ru: {
    identityLabel: "Идентичность",
    targetUserLabel: "Для кого",
    primaryValueLabel: "Главная ценность",
    mainActionLabel: "Основное действие",
    selectPlaceholder: "Выберите вариант",
    launchCopyLabel: "Текст для запуска",
    previewConfirmation: "Это предпросмотр. Опубликуйте версию, чтобы получать реальные отклики.",
    madeWith: "Создано с Ventrio",
    acceptedCommunity: "Вы с нами.",
    acceptedService: "Спасибо — ваш отклик отправлен.",
    acceptedContent: "Вы в списке.",
    acceptedProduct: "Вы в списке.",
    invalid: "Проверьте заполненные поля и попробуйте снова.",
    rateLimited: "Вы уже отправили несколько откликов. Попробуйте позже.",
    unavailable: "Форма временно недоступна. Попробуйте ещё раз.",
    submitting: "Отправляю…",
  },
} as const satisfies Record<Locale, Record<string, string>>;
